### ISSUE TITLE
Migration to m105

### ISSUE THREAD

**Issue by SergeevPavel** [JetBrains/skia-pack#12]
* since m100 `git-sync-deps` install emsdk on his own so we don't need `prepare_wasm.sh` anymore
* initialization of emsdk failed on linux aarch64, waiting for https://bugs.chromium.org/p/skia/issues/detail?id=13646
* some assert in skParagraph fails in m105 debug build https://bugs.chromium.org/p/skia/issues/detail?id=13649

**Comment by eymar** [comment]
just in case for emsdk failure on linux-arm64, if we don't want to wait for a fix in the upstream, we may use a workaround on our side https://github.com/JetBrains/skia-pack/pull/14  The build is still running, but I think it should go well. 
cc @igordmn what do you think?

**Comment by SergeevPavel** [comment]
skia folks come up with very same solution https://bugs.chromium.org/p/skia/issues/detail?id=13646

**Comment by igordmn** [comment]
I, think, we can close this PR?
