### ISSUE TITLE
value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' #6

### ISSUE THREAD

**Issue by Alberl-Lee** [JetBrains/skia-pack#34]
windows 10 x64，debug model error :
`1>skia_x64_debug.lib(skia.SkColor.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2'‘

1>skia_x64_debug.lib(skia.SkColor.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' `

**Comment by mgood7123** [comment]
linking requires (`C/C++ > Code Generation > Runtime Library`) `Multi-threaded` (`/MT`)

debugging requires (`C/C++ > Command Line > Additional Options`) `/D_ITERATOR_DEBUG_LEVEL=0` and (`C/C++ > Preprocessor`) preprocessor definition `NDEBUG` instead of `_DEBUG`
